---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# CATIE2023_vMods

<!-- badges: start -->

<!-- badges: end -->

The goal of CATIE2023_vMods is to bundle the data set and code used for the CATIE 2023 Virtual days into an R project.

## Setup

1.  Download the zip file or clone the GitHub repo to your computer
2.  Launch the CATIE2023_vMods.Rproj file in R studio
3.  The R environment should activate and download the necessary packages

## Virtual modules

There are two virtual modules that give an overview of common data analytic work flows.

-   Virtual module 2 (V2): Primary Aims analytics.

    -   Main effects of first stage treatment
    -   Main effects of second stage treatment
    -   Mean of embedded adaptive interventions

-   Virtual module 3 (V3): Secondary Aims analytics

    -   Testing moderators for use as tailoring variables

    -   Estimate the mean outcome of a more deeply-tailored adaptive intervention

Follow along with the rendered `.html` documents or run the code in the interactive `.qmd` file.

## Code along

Simple R scripts to practice implementing V2 & V3 concepts.

-   `V2_primary_aims_code_along.R`

-   `V3_seconday_aims_code_along.R`

### Data

-   `adhd-simulated-2023.csv` *simulated* data set similar to the ADHD SMART study conducted by Bill Pelham. For instructional purposes only.
